<a href="https://colab.research.google.com/github/Regi3051/RegiHeksaAnanda_2411533004_ML2526/blob/main/Praktikum3/TugasPraktikum3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score, recall_score, f1_score

In [ ]:
dataset_url = 'https://raw.githubusercontent.com/Regi3051/RegiHeksaAnanda_2411533004_ML2526/refs/heads/main/Praktikum3/Breast_cancer_data.csv'
df = pd.read_csv(dataset_url)
X = df.drop('diagnosis', axis=1)
y = df['diagnosis']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
logreg_unscaled = LogisticRegression(max_iter=1000, random_state=42)
logreg_unscaled.fit(X_train, y_train)
y_pred_unscaled = logreg_unscaled.predict(X_test)

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
logreg_scaled = LogisticRegression(random_state=42)
logreg_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = logreg_scaled.predict(X_test_scaled)

In [ ]:
print("--- Akurasi Tanpa Scaling ---")
print(accuracy_score(y_test, y_pred_unscaled))
print("--- Akurasi Dengan Scaling ---")
print(accuracy_score(y_test, y_pred_scaled))

--- Akurasi Tanpa Scaling ---
0.935672514619883
--- Akurasi Dengan Scaling ---
0.9473684210526315


In [ ]:
y_pred_proba = logreg_scaled.predict_proba(X_test_scaled)[:, 1]

In [ ]:
thresholds = [0.3, 0.5, 0.7]

for t in thresholds:
    y_pred_custom = (y_pred_proba >= t).astype(int)

    print(f"\n=== Evaluasi Model dengan Threshold: {t} ===")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred_custom))
    print(f"Precision: {precision_score(y_test, y_pred_custom):.4f}")
    print(f"Recall: {recall_score(y_test, y_pred_custom):.4f}")
    print(f"F1-Score: {f1_score(y_test, y_pred_custom):.4f}")


=== Evaluasi Model dengan Threshold: 0.3 ===
Confusion Matrix:
[[ 52  11]
 [  0 108]]
Precision: 0.9076
Recall: 1.0000
F1-Score: 0.9515

=== Evaluasi Model dengan Threshold: 0.5 ===
Confusion Matrix:
[[ 59   4]
 [  5 103]]
Precision: 0.9626
Recall: 0.9537
F1-Score: 0.9581

=== Evaluasi Model dengan Threshold: 0.7 ===
Confusion Matrix:
[[62  1]
 [10 98]]
Precision: 0.9899
Recall: 0.9074
F1-Score: 0.9469
